/**
 * Suburb Location Data
 * North, West, and South suburbs of Chicago
 */

import { LocationData } from "./expandLocations";

// NORTHERN SUBURBS (40+)
export const NORTHERN_SUBURBS: LocationData[] = [
  {
    id: "evanston",
    name: "Evanston",
    state: "IL",
    type: "suburb",
    region: "north",
    coordinates: { lat: 42.0451, lng: -87.6877 },
    zipCodes: ["60201", "60202"],
    nearbyAirports: { ORD: 20, MDW: 25 },
    applicableServices: {
      airport: 19,
      corporate: 18,
      wedding: 18,
      partyBus: 17,
    },
    description:
      "Home to Northwestern University with lakefront beaches and vibrant downtown",
  },
  {
    id: "skokie",
    name: "Skokie",
    state: "IL",
    type: "suburb",
    region: "north",
    coordinates: { lat: 42.0324, lng: -87.7417 },
    zipCodes: ["60076", "60077"],
    nearbyAirports: { ORD: 18, MDW: 25 },
    applicableServices: {
      airport: 18,
      corporate: 17,
      wedding: 17,
      partyBus: 16,
    },
    description:
      "Diverse suburb with shopping, dining, and cultural attractions",
  },
  {
    id: "wilmette",
    name: "Wilmette",
    state: "IL",
    type: "suburb",
    region: "north",
    coordinates: { lat: 42.0723, lng: -87.7223 },
    zipCodes: ["60091"],
    nearbyAirports: { ORD: 22, MDW: 28 },
    applicableServices: {
      airport: 18,
      corporate: 17,
      wedding: 18,
      partyBus: 15,
    },
    description: "Affluent lakefront suburb known for the Baha'i Temple",
  },
  {
    id: "winnetka",
    name: "Winnetka",
    state: "IL",
    type: "suburb",
    region: "north",
    coordinates: { lat: 42.108, lng: -87.7359 },
    zipCodes: ["60093"],
    nearbyAirports: { ORD: 24, MDW: 30 },
    applicableServices: {
      airport: 19,
      corporate: 18,
      wedding: 19,
      partyBus: 14,
    },
    description:
      "Exclusive North Shore village with upscale homes and lakefront",
  },
  {
    id: "glencoe",
    name: "Glencoe",
    state: "IL",
    type: "suburb",
    region: "north",
    coordinates: { lat: 42.135, lng: -87.7581 },
    zipCodes: ["60022"],
    nearbyAirports: { ORD: 26, MDW: 32 },
    applicableServices: {
      airport: 19,
      corporate: 18,
      wedding: 19,
      partyBus: 14,
    },
    description:
      "Affluent North Shore community with Chicago Botanic Garden nearby",
  },
  {
    id: "northbrook",
    name: "Northbrook",
    state: "IL",
    type: "suburb",
    region: "north",
    coordinates: { lat: 42.1278, lng: -87.8289 },
    zipCodes: ["60062"],
    nearbyAirports: { ORD: 20, MDW: 30 },
    applicableServices: {
      airport: 19,
      corporate: 18,
      wedding: 18,
      partyBus: 16,
    },
    description:
      "Suburban community with shopping, dining, and corporate offices",
  },
  {
    id: "glenview",
    name: "Glenview",
    state: "IL",
    type: "suburb",
    region: "north",
    coordinates: { lat: 42.0697, lng: -87.7878 },
    zipCodes: ["60025", "60026"],
    nearbyAirports: { ORD: 15, MDW: 26 },
    applicableServices: {
      airport: 20,
      corporate: 18,
      wedding: 17,
      partyBus: 16,
    },
    description:
      "Large suburb close to O'Hare with shopping and The Glen development",
  },
  {
    id: "niles",
    name: "Niles",
    state: "IL",
    type: "suburb",
    region: "north",
    coordinates: { lat: 42.0189, lng: -87.8023 },
    zipCodes: ["60714"],
    nearbyAirports: { ORD: 12, MDW: 23 },
    applicableServices: {
      airport: 19,
      corporate: 17,
      wedding: 16,
      partyBus: 16,
    },
    description: "Diverse suburb near O'Hare with Leaning Tower of Niles",
  },
  {
    id: "morton-grove",
    name: "Morton Grove",
    state: "IL",
    type: "suburb",
    region: "north",
    coordinates: { lat: 42.0406, lng: -87.7825 },
    zipCodes: ["60053"],
    nearbyAirports: { ORD: 14, MDW: 24 },
    applicableServices: {
      airport: 19,
      corporate: 17,
      wedding: 16,
      partyBus: 16,
    },
    description: "Residential suburb near O'Hare with parks and shopping",
  },
  {
    id: "lincolnwood",
    name: "Lincolnwood",
    state: "IL",
    type: "suburb",
    region: "north",
    coordinates: { lat: 42.0042, lng: -87.73 },
    zipCodes: ["60712"],
    nearbyAirports: { ORD: 15, MDW: 23 },
    applicableServices: {
      airport: 19,
      corporate: 17,
      wedding: 16,
      partyBus: 16,
    },
    description: "Small suburb with major shopping center near Chicago border",
  },
  {
    id: "park-ridge",
    name: "Park Ridge",
    state: "IL",
    type: "suburb",
    region: "north",
    coordinates: { lat: 42.0111, lng: -87.8406 },
    zipCodes: ["60068"],
    nearbyAirports: { ORD: 8, MDW: 22 },
    applicableServices: {
      airport: 20,
      corporate: 17,
      wedding: 17,
      partyBus: 15,
    },
    description:
      "Upscale suburb adjacent to O'Hare Airport with historic downtown",
  },
  {
    id: "des-plaines",
    name: "Des Plaines",
    state: "IL",
    type: "suburb",
    region: "north",
    coordinates: { lat: 42.0334, lng: -87.8834 },
    zipCodes: ["60016", "60018"],
    nearbyAirports: { ORD: 6, MDW: 24 },
    applicableServices: {
      airport: 20,
      corporate: 17,
      wedding: 16,
      partyBus: 16,
    },
    description:
      "Diverse suburb immediately adjacent to O'Hare Airport with hotels and restaurants",
  },
  {
    id: "mount-prospect",
    name: "Mount Prospect",
    state: "IL",
    type: "suburb",
    region: "north",
    coordinates: { lat: 42.0664, lng: -87.9373 },
    zipCodes: ["60056"],
    nearbyAirports: { ORD: 10, MDW: 27 },
    applicableServices: {
      airport: 19,
      corporate: 17,
      wedding: 17,
      partyBus: 16,
    },
    description: "Family-oriented suburb with downtown area and parks",
  },
  {
    id: "arlington-heights",
    name: "Arlington Heights",
    state: "IL",
    type: "suburb",
    region: "north",
    coordinates: { lat: 42.0883, lng: -87.9806 },
    zipCodes: ["60004", "60005"],
    nearbyAirports: { ORD: 12, MDW: 30 },
    applicableServices: {
      airport: 19,
      corporate: 18,
      wedding: 18,
      partyBus: 17,
    },
    description:
      "Large Northwest suburb with Arlington Park and vibrant downtown",
  },
  {
    id: "palatine",
    name: "Palatine",
    state: "IL",
    type: "suburb",
    region: "north",
    coordinates: { lat: 42.1103, lng: -88.0342 },
    zipCodes: ["60067", "60074"],
    nearbyAirports: { ORD: 14, MDW: 32 },
    applicableServices: {
      airport: 19,
      corporate: 17,
      wedding: 17,
      partyBus: 16,
    },
    description: "Growing suburb with downtown area and corporate presence",
  },
  {
    id: "schaumburg",
    name: "Schaumburg",
    state: "IL",
    type: "suburb",
    region: "north",
    coordinates: { lat: 42.0333, lng: -88.0834 },
    zipCodes: ["60173", "60193", "60194"],
    nearbyAirports: { ORD: 10, MDW: 30 },
    applicableServices: {
      airport: 20,
      corporate: 20,
      wedding: 17,
      partyBus: 16,
    },
    description:
      "Major business hub with Woodfield Mall, hotels, and corporate offices",
  },
  {
    id: "rolling-meadows",
    name: "Rolling Meadows",
    state: "IL",
    type: "suburb",
    region: "north",
    coordinates: { lat: 42.0761, lng: -88.0134 },
    zipCodes: ["60008"],
    nearbyAirports: { ORD: 11, MDW: 29 },
    applicableServices: {
      airport: 19,
      corporate: 17,
      wedding: 16,
      partyBus: 15,
    },
    description: "Residential suburb near business corridors",
  },
  {
    id: "elk-grove-village",
    name: "Elk Grove Village",
    state: "IL",
    type: "suburb",
    region: "north",
    coordinates: { lat: 42.0039, lng: -87.9703 },
    zipCodes: ["60007"],
    nearbyAirports: { ORD: 5, MDW: 26 },
    applicableServices: {
      airport: 20,
      corporate: 19,
      wedding: 16,
      partyBus: 16,
    },
    description:
      "Major industrial and business park adjacent to O'Hare Airport",
  },
  {
    id: "hoffman-estates",
    name: "Hoffman Estates",
    state: "IL",
    type: "suburb",
    region: "north",
    coordinates: { lat: 42.0629, lng: -88.1459 },
    zipCodes: ["60169", "60192"],
    nearbyAirports: { ORD: 14, MDW: 32 },
    applicableServices: {
      airport: 19,
      corporate: 18,
      wedding: 17,
      partyBus: 16,
    },
    description:
      "Large suburb with Sears corporate headquarters and entertainment venues",
  },
  {
    id: "buffalo-grove",
    name: "Buffalo Grove",
    state: "IL",
    type: "suburb",
    region: "north",
    coordinates: { lat: 42.1519, lng: -87.9595 },
    zipCodes: ["60089"],
    nearbyAirports: { ORD: 16, MDW: 32 },
    applicableServices: {
      airport: 18,
      corporate: 17,
      wedding: 17,
      partyBus: 15,
    },
    description: "Affluent suburb with excellent schools and shopping",
  },
  {
    id: "wheeling",
    name: "Wheeling",
    state: "IL",
    type: "suburb",
    region: "north",
    coordinates: { lat: 42.1392, lng: -87.9292 },
    zipCodes: ["60090"],
    nearbyAirports: { ORD: 14, MDW: 30 },
    applicableServices: {
      airport: 19,
      corporate: 17,
      wedding: 17,
      partyBus: 16,
    },
    description: "Diverse suburb with Restaurant Row and business parks",
  },
  {
    id: "prospect-heights",
    name: "Prospect Heights",
    state: "IL",
    type: "suburb",
    region: "north",
    coordinates: { lat: 42.0953, lng: -87.9376 },
    zipCodes: ["60070"],
    nearbyAirports: { ORD: 12, MDW: 29 },
    applicableServices: {
      airport: 19,
      corporate: 17,
      wedding: 16,
      partyBus: 15,
    },
    description: "Small residential suburb near major highways",
  },
  {
    id: "highland-park",
    name: "Highland Park",
    state: "IL",
    type: "suburb",
    region: "north",
    coordinates: { lat: 42.1817, lng: -87.8003 },
    zipCodes: ["60035"],
    nearbyAirports: { ORD: 28, MDW: 35 },
    applicableServices: {
      airport: 18,
      corporate: 17,
      wedding: 19,
      partyBus: 15,
    },
    description:
      "Affluent North Shore suburb with Ravinia Festival and lakefront",
  },
  {
    id: "deerfield",
    name: "Deerfield",
    state: "IL",
    type: "suburb",
    region: "north",
    coordinates: { lat: 42.1711, lng: -87.8445 },
    zipCodes: ["60015"],
    nearbyAirports: { ORD: 22, MDW: 33 },
    applicableServices: {
      airport: 19,
      corporate: 18,
      wedding: 18,
      partyBus: 15,
    },
    description:
      "Corporate suburb with Fortune 500 headquarters and upscale homes",
  },
  {
    id: "lake-forest",
    name: "Lake Forest",
    state: "IL",
    type: "suburb",
    region: "north",
    coordinates: { lat: 42.2587, lng: -87.8406 },
    zipCodes: ["60045"],
    nearbyAirports: { ORD: 32, MDW: 40 },
    applicableServices: {
      airport: 18,
      corporate: 17,
      wedding: 19,
      partyBus: 14,
    },
    description:
      "Exclusive North Shore community with Lake Forest College and historic estates",
  },
  {
    id: "lake-bluff",
    name: "Lake Bluff",
    state: "IL",
    type: "suburb",
    region: "north",
    coordinates: { lat: 42.2789, lng: -87.8359 },
    zipCodes: ["60044"],
    nearbyAirports: { ORD: 34, MDW: 42 },
    applicableServices: {
      airport: 17,
      corporate: 16,
      wedding: 18,
      partyBus: 13,
    },
    description: "Small lakefront village with charming downtown and beaches",
  },
  {
    id: "libertyville",
    name: "Libertyville",
    state: "IL",
    type: "suburb",
    region: "north",
    coordinates: { lat: 42.2831, lng: -87.9534 },
    zipCodes: ["60048"],
    nearbyAirports: { ORD: 30, MDW: 40 },
    applicableServices: {
      airport: 17,
      corporate: 16,
      wedding: 17,
      partyBus: 15,
    },
    description:
      "Historic downtown with shops, restaurants, and nearby corporate campuses",
  },
  {
    id: "vernon-hills",
    name: "Vernon Hills",
    state: "IL",
    type: "suburb",
    region: "north",
    coordinates: { lat: 42.2191, lng: -87.9595 },
    zipCodes: ["60061"],
    nearbyAirports: { ORD: 24, MDW: 36 },
    applicableServices: {
      airport: 18,
      corporate: 17,
      wedding: 16,
      partyBus: 15,
    },
    description: "Modern suburb with retail centers and corporate offices",
  },
  {
    id: "mundelein",
    name: "Mundelein",
    state: "IL",
    type: "suburb",
    region: "north",
    coordinates: { lat: 42.2631, lng: -88.004 },
    zipCodes: ["60060"],
    nearbyAirports: { ORD: 26, MDW: 38 },
    applicableServices: {
      airport: 17,
      corporate: 16,
      wedding: 16,
      partyBus: 15,
    },
    description: "Growing suburb with downtown area and lake access",
  },
  {
    id: "waukegan",
    name: "Waukegan",
    state: "IL",
    type: "suburb",
    region: "north",
    coordinates: { lat: 42.3636, lng: -87.8448 },
    zipCodes: ["60085", "60087"],
    nearbyAirports: { ORD: 38, MDW: 46 },
    applicableServices: {
      airport: 16,
      corporate: 15,
      wedding: 15,
      partyBus: 14,
    },
    description:
      "Lake County seat with harbor, Genesee Theatre, and diverse population",
  },
  {
    id: "gurnee",
    name: "Gurnee",
    state: "IL",
    type: "suburb",
    region: "north",
    coordinates: { lat: 42.3703, lng: -87.902 },
    zipCodes: ["60031"],
    nearbyAirports: { ORD: 36, MDW: 46 },
    applicableServices: {
      airport: 17,
      corporate: 16,
      wedding: 16,
      partyBus: 16,
    },
    description: "Home to Six Flags Great America and Gurnee Mills outlet mall",
  },
  {
    id: "round-lake",
    name: "Round Lake",
    state: "IL",
    type: "suburb",
    region: "north",
    coordinates: { lat: 42.3563, lng: -88.0901 },
    zipCodes: ["60073"],
    nearbyAirports: { ORD: 34, MDW: 45 },
    applicableServices: {
      airport: 16,
      corporate: 14,
      wedding: 15,
      partyBus: 14,
    },
    description: "Chain of lake communities in northern Lake County",
  },
];

// WESTERN SUBURBS (50+)
export const WESTERN_SUBURBS: LocationData[] = [
  {
    id: "oak-park",
    name: "Oak Park",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.885, lng: -87.7845 },
    zipCodes: ["60302", "60304"],
    nearbyAirports: { ORD: 14, MDW: 14 },
    applicableServices: {
      airport: 19,
      corporate: 18,
      wedding: 18,
      partyBus: 17,
    },
    description:
      "Historic suburb with Frank Lloyd Wright homes and vibrant downtown",
  },
  {
    id: "river-forest",
    name: "River Forest",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.8978, lng: -87.8139 },
    zipCodes: ["60305"],
    nearbyAirports: { ORD: 13, MDW: 15 },
    applicableServices: {
      airport: 18,
      corporate: 17,
      wedding: 18,
      partyBus: 16,
    },
    description:
      "Affluent village with Dominican University and architectural heritage",
  },
  {
    id: "forest-park",
    name: "Forest Park",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.8794, lng: -87.8134 },
    zipCodes: ["60130"],
    nearbyAirports: { ORD: 13, MDW: 14 },
    applicableServices: {
      airport: 18,
      corporate: 16,
      wedding: 16,
      partyBus: 16,
    },
    description: "Transit-accessible suburb at the end of CTA Blue Line",
  },
  {
    id: "berwyn",
    name: "Berwyn",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.8506, lng: -87.7937 },
    zipCodes: ["60402"],
    nearbyAirports: { ORD: 15, MDW: 12 },
    applicableServices: {
      airport: 18,
      corporate: 16,
      wedding: 16,
      partyBus: 16,
    },
    description: "Diverse suburb with Czech heritage and Route 66 history",
  },
  {
    id: "cicero",
    name: "Cicero",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.8456, lng: -87.7539 },
    zipCodes: ["60804"],
    nearbyAirports: { ORD: 14, MDW: 11 },
    applicableServices: {
      airport: 18,
      corporate: 16,
      wedding: 16,
      partyBus: 16,
    },
    description: "Large predominantly Hispanic suburb adjacent to Chicago",
  },
  {
    id: "oak-brook",
    name: "Oak Brook",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.8328, lng: -87.9289 },
    zipCodes: ["60523"],
    nearbyAirports: { ORD: 16, MDW: 18 },
    applicableServices: {
      airport: 20,
      corporate: 20,
      wedding: 19,
      partyBus: 16,
    },
    description:
      "Upscale suburb with Oakbrook Center mall and corporate headquarters",
  },
  {
    id: "elmhurst",
    name: "Elmhurst",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.8994, lng: -87.9403 },
    zipCodes: ["60126"],
    nearbyAirports: { ORD: 13, MDW: 16 },
    applicableServices: {
      airport: 19,
      corporate: 18,
      wedding: 18,
      partyBus: 17,
    },
    description: "Charming suburb with Elmhurst College and walkable downtown",
  },
  {
    id: "villa-park",
    name: "Villa Park",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.8897, lng: -87.9789 },
    zipCodes: ["60181"],
    nearbyAirports: { ORD: 13, MDW: 17 },
    applicableServices: {
      airport: 18,
      corporate: 17,
      wedding: 17,
      partyBus: 16,
    },
    description: "Residential suburb with parks and Metra access",
  },
  {
    id: "lombard",
    name: "Lombard",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.88, lng: -88.0078 },
    zipCodes: ["60148"],
    nearbyAirports: { ORD: 14, MDW: 18 },
    applicableServices: {
      airport: 19,
      corporate: 17,
      wedding: 17,
      partyBus: 16,
    },
    description: 'Known as the "Lilac Village" with parks and business parks',
  },
  {
    id: "glen-ellyn",
    name: "Glen Ellyn",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.8775, lng: -88.067 },
    zipCodes: ["60137"],
    nearbyAirports: { ORD: 17, MDW: 20 },
    applicableServices: {
      airport: 18,
      corporate: 17,
      wedding: 18,
      partyBus: 16,
    },
    description: "Charming suburb with College of DuPage and historic downtown",
  },
  {
    id: "wheaton",
    name: "Wheaton",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.8661, lng: -88.107 },
    zipCodes: ["60187", "60189"],
    nearbyAirports: { ORD: 18, MDW: 21 },
    applicableServices: {
      airport: 19,
      corporate: 18,
      wedding: 19,
      partyBus: 16,
    },
    description: "DuPage County seat with Wheaton College and Cantigny Park",
  },
  {
    id: "carol-stream",
    name: "Carol Stream",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.9125, lng: -88.1348 },
    zipCodes: ["60188"],
    nearbyAirports: { ORD: 16, MDW: 22 },
    applicableServices: {
      airport: 18,
      corporate: 17,
      wedding: 16,
      partyBus: 15,
    },
    description: "Residential and commercial suburb with parks and shopping",
  },
  {
    id: "glendale-heights",
    name: "Glendale Heights",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.9128, lng: -88.0781 },
    zipCodes: ["60139"],
    nearbyAirports: { ORD: 15, MDW: 21 },
    applicableServices: {
      airport: 18,
      corporate: 17,
      wedding: 16,
      partyBus: 15,
    },
    description: "Diverse suburb with parks and easy highway access",
  },
  {
    id: "bloomingdale",
    name: "Bloomingdale",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.9575, lng: -88.0809 },
    zipCodes: ["60108"],
    nearbyAirports: { ORD: 13, MDW: 23 },
    applicableServices: {
      airport: 19,
      corporate: 17,
      wedding: 17,
      partyBus: 16,
    },
    description: "Family-friendly suburb with Stratford Square Mall",
  },
  {
    id: "addison",
    name: "Addison",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.9317, lng: -87.9889 },
    zipCodes: ["60101"],
    nearbyAirports: { ORD: 10, MDW: 20 },
    applicableServices: {
      airport: 19,
      corporate: 18,
      wedding: 16,
      partyBus: 16,
    },
    description: "Diverse suburb with business parks and entertainment venues",
  },
  {
    id: "bensenville",
    name: "Bensenville",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.955, lng: -87.94 },
    zipCodes: ["60106"],
    nearbyAirports: { ORD: 7, MDW: 22 },
    applicableServices: {
      airport: 20,
      corporate: 17,
      wedding: 15,
      partyBus: 15,
    },
    description: "Industrial suburb adjacent to O'Hare Airport",
  },
  {
    id: "wood-dale",
    name: "Wood Dale",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.9636, lng: -87.9789 },
    zipCodes: ["60191"],
    nearbyAirports: { ORD: 8, MDW: 23 },
    applicableServices: {
      airport: 20,
      corporate: 17,
      wedding: 15,
      partyBus: 15,
    },
    description:
      "Small suburb near O'Hare with residential and industrial areas",
  },
  {
    id: "itasca",
    name: "Itasca",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.9753, lng: -88.0075 },
    zipCodes: ["60143"],
    nearbyAirports: { ORD: 11, MDW: 24 },
    applicableServices: {
      airport: 19,
      corporate: 18,
      wedding: 16,
      partyBus: 15,
    },
    description: "Corporate suburb with business parks and hotels",
  },
  {
    id: "roselle",
    name: "Roselle",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.9847, lng: -88.0795 },
    zipCodes: ["60172"],
    nearbyAirports: { ORD: 13, MDW: 24 },
    applicableServices: {
      airport: 18,
      corporate: 17,
      wedding: 16,
      partyBus: 15,
    },
    description: "Residential suburb with parks and trails",
  },
  {
    id: "hanover-park",
    name: "Hanover Park",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.9994, lng: -88.145 },
    zipCodes: ["60133"],
    nearbyAirports: { ORD: 14, MDW: 26 },
    applicableServices: {
      airport: 18,
      corporate: 16,
      wedding: 16,
      partyBus: 15,
    },
    description: "Diverse suburb with residential neighborhoods",
  },
  {
    id: "bartlett",
    name: "Bartlett",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.995, lng: -88.1856 },
    zipCodes: ["60103"],
    nearbyAirports: { ORD: 16, MDW: 28 },
    applicableServices: {
      airport: 18,
      corporate: 17,
      wedding: 17,
      partyBus: 15,
    },
    description: "Growing suburb with parks and family-friendly amenities",
  },
  {
    id: "streamwood",
    name: "Streamwood",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 42.0256, lng: -88.1784 },
    zipCodes: ["60107"],
    nearbyAirports: { ORD: 14, MDW: 28 },
    applicableServices: {
      airport: 18,
      corporate: 16,
      wedding: 16,
      partyBus: 15,
    },
    description: "Residential suburb with parks and shopping",
  },
  {
    id: "west-chicago",
    name: "West Chicago",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.8847, lng: -88.204 },
    zipCodes: ["60185"],
    nearbyAirports: { ORD: 18, MDW: 24 },
    applicableServices: {
      airport: 17,
      corporate: 16,
      wedding: 16,
      partyBus: 15,
    },
    description: "Historic railroad town with downtown area",
  },
  {
    id: "warrenville",
    name: "Warrenville",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.8236, lng: -88.1873 },
    zipCodes: ["60555"],
    nearbyAirports: { ORD: 18, MDW: 22 },
    applicableServices: {
      airport: 17,
      corporate: 17,
      wedding: 16,
      partyBus: 15,
    },
    description: "Small suburb with Fermilab and prairie trails",
  },
  {
    id: "naperville",
    name: "Naperville",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.7508, lng: -88.1535 },
    zipCodes: ["60540", "60563", "60564"],
    nearbyAirports: { ORD: 24, MDW: 22 },
    applicableServices: {
      airport: 20,
      corporate: 20,
      wedding: 20,
      partyBus: 17,
    },
    description:
      "Highly-rated suburb with Riverwalk, downtown dining, and corporate headquarters",
  },
  {
    id: "lisle",
    name: "Lisle",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.8011, lng: -88.0745 },
    zipCodes: ["60532"],
    nearbyAirports: { ORD: 17, MDW: 20 },
    applicableServices: {
      airport: 19,
      corporate: 18,
      wedding: 17,
      partyBus: 16,
    },
    description: "Suburb with Morton Arboretum and business centers",
  },
  {
    id: "woodridge",
    name: "Woodridge",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.7469, lng: -88.0503 },
    zipCodes: ["60517"],
    nearbyAirports: { ORD: 19, MDW: 20 },
    applicableServices: {
      airport: 18,
      corporate: 17,
      wedding: 16,
      partyBus: 15,
    },
    description: "Family-oriented suburb with parks and trails",
  },
  {
    id: "downers-grove",
    name: "Downers Grove",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.8089, lng: -88.0112 },
    zipCodes: ["60515", "60516"],
    nearbyAirports: { ORD: 17, MDW: 18 },
    applicableServices: {
      airport: 19,
      corporate: 18,
      wedding: 18,
      partyBus: 17,
    },
    description:
      "Vibrant suburb with walkable downtown, restaurants, and Metra access",
  },
  {
    id: "westmont",
    name: "Westmont",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.7958, lng: -87.9759 },
    zipCodes: ["60559"],
    nearbyAirports: { ORD: 17, MDW: 16 },
    applicableServices: {
      airport: 18,
      corporate: 17,
      wedding: 17,
      partyBus: 16,
    },
    description: "Small suburb with downtown area and Metra station",
  },
  {
    id: "clarendon-hills",
    name: "Clarendon Hills",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.7969, lng: -87.9548 },
    zipCodes: ["60514"],
    nearbyAirports: { ORD: 18, MDW: 17 },
    applicableServices: {
      airport: 18,
      corporate: 17,
      wedding: 18,
      partyBus: 15,
    },
    description: "Small affluent village with charming downtown",
  },
  {
    id: "hinsdale",
    name: "Hinsdale",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.8009, lng: -87.937 },
    zipCodes: ["60521"],
    nearbyAirports: { ORD: 18, MDW: 17 },
    applicableServices: {
      airport: 20,
      corporate: 19,
      wedding: 20,
      partyBus: 15,
    },
    description: "Exclusive suburb with upscale shopping and historic homes",
  },
  {
    id: "western-springs",
    name: "Western Springs",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.8092, lng: -87.8995 },
    zipCodes: ["60558"],
    nearbyAirports: { ORD: 17, MDW: 15 },
    applicableServices: {
      airport: 19,
      corporate: 18,
      wedding: 18,
      partyBus: 16,
    },
    description: "Affluent suburb with small-town charm and excellent schools",
  },
  {
    id: "la-grange",
    name: "La Grange",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.805, lng: -87.8692 },
    zipCodes: ["60525"],
    nearbyAirports: { ORD: 16, MDW: 14 },
    applicableServices: {
      airport: 19,
      corporate: 17,
      wedding: 18,
      partyBus: 16,
    },
    description: "Historic suburb with walkable downtown and Metra access",
  },
  {
    id: "la-grange-park",
    name: "La Grange Park",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.8347, lng: -87.8617 },
    zipCodes: ["60526"],
    nearbyAirports: { ORD: 16, MDW: 14 },
    applicableServices: {
      airport: 18,
      corporate: 17,
      wedding: 17,
      partyBus: 16,
    },
    description: "Residential suburb adjacent to La Grange",
  },
  {
    id: "brookfield",
    name: "Brookfield",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.8236, lng: -87.8512 },
    zipCodes: ["60513"],
    nearbyAirports: { ORD: 15, MDW: 13 },
    applicableServices: {
      airport: 18,
      corporate: 17,
      wedding: 17,
      partyBus: 16,
    },
    description: "Home to Brookfield Zoo with residential neighborhoods",
  },
  {
    id: "riverside",
    name: "Riverside",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.8314, lng: -87.8231 },
    zipCodes: ["60546"],
    nearbyAirports: { ORD: 15, MDW: 13 },
    applicableServices: {
      airport: 18,
      corporate: 17,
      wedding: 18,
      partyBus: 15,
    },
    description: "Historic planned community designed by Frederick Law Olmsted",
  },
  {
    id: "lyons",
    name: "Lyons",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.8119, lng: -87.8184 },
    zipCodes: ["60534"],
    nearbyAirports: { ORD: 15, MDW: 12 },
    applicableServices: {
      airport: 18,
      corporate: 16,
      wedding: 16,
      partyBus: 15,
    },
    description: "Small suburb along the Des Plaines River",
  },
  {
    id: "burr-ridge",
    name: "Burr Ridge",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.7489, lng: -87.9178 },
    zipCodes: ["60527"],
    nearbyAirports: { ORD: 19, MDW: 17 },
    applicableServices: {
      airport: 19,
      corporate: 18,
      wedding: 19,
      partyBus: 15,
    },
    description: "Affluent suburb with upscale homes and shopping",
  },
  {
    id: "willowbrook",
    name: "Willowbrook",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.7697, lng: -87.9445 },
    zipCodes: ["60527"],
    nearbyAirports: { ORD: 17, MDW: 16 },
    applicableServices: {
      airport: 18,
      corporate: 17,
      wedding: 16,
      partyBus: 15,
    },
    description: "Small suburb with retail and residential areas",
  },
  {
    id: "darien",
    name: "Darien",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.7517, lng: -87.9739 },
    zipCodes: ["60561"],
    nearbyAirports: { ORD: 18, MDW: 18 },
    applicableServices: {
      airport: 18,
      corporate: 17,
      wedding: 17,
      partyBus: 15,
    },
    description: "Residential suburb with parks and trails",
  },
  {
    id: "bolingbrook",
    name: "Bolingbrook",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.6986, lng: -88.0684 },
    zipCodes: ["60440"],
    nearbyAirports: { ORD: 22, MDW: 20 },
    applicableServices: {
      airport: 18,
      corporate: 17,
      wedding: 17,
      partyBus: 16,
    },
    description: "Large diverse suburb with shopping and entertainment",
  },
  {
    id: "romeoville",
    name: "Romeoville",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.6475, lng: -88.0895 },
    zipCodes: ["60446"],
    nearbyAirports: { ORD: 24, MDW: 20 },
    applicableServices: {
      airport: 17,
      corporate: 16,
      wedding: 16,
      partyBus: 15,
    },
    description: "Growing suburb with Isle a la Cache and waterways",
  },
  {
    id: "lemont",
    name: "Lemont",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.6739, lng: -88.0078 },
    zipCodes: ["60439"],
    nearbyAirports: { ORD: 22, MDW: 18 },
    applicableServices: {
      airport: 17,
      corporate: 16,
      wedding: 17,
      partyBus: 15,
    },
    description: "Historic town along the I&M Canal with downtown charm",
  },
  {
    id: "homer-glen",
    name: "Homer Glen",
    state: "IL",
    type: "suburb",
    region: "southwest",
    coordinates: { lat: 41.6, lng: -87.9395 },
    zipCodes: ["60491"],
    nearbyAirports: { ORD: 25, MDW: 18 },
    applicableServices: {
      airport: 17,
      corporate: 16,
      wedding: 17,
      partyBus: 15,
    },
    description: "Newer suburb with residential neighborhoods and preserves",
  },
  {
    id: "lockport",
    name: "Lockport",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.5894, lng: -88.0578 },
    zipCodes: ["60441"],
    nearbyAirports: { ORD: 26, MDW: 22 },
    applicableServices: {
      airport: 16,
      corporate: 15,
      wedding: 16,
      partyBus: 14,
    },
    description: "Historic canal town with downtown area",
  },
  {
    id: "plainfield",
    name: "Plainfield",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.627, lng: -88.212 },
    zipCodes: ["60544", "60585"],
    nearbyAirports: { ORD: 28, MDW: 25 },
    applicableServices: {
      airport: 17,
      corporate: 16,
      wedding: 17,
      partyBus: 15,
    },
    description: "Fast-growing suburb with new developments and parks",
  },
  {
    id: "oswego",
    name: "Oswego",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.6828, lng: -88.3512 },
    zipCodes: ["60543"],
    nearbyAirports: { ORD: 32, MDW: 28 },
    applicableServices: {
      airport: 16,
      corporate: 15,
      wedding: 16,
      partyBus: 14,
    },
    description: "Growing suburb along the Fox River",
  },
  {
    id: "aurora",
    name: "Aurora",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.7606, lng: -88.3201 },
    zipCodes: ["60502", "60504", "60505", "60506"],
    nearbyAirports: { ORD: 30, MDW: 28 },
    applicableServices: {
      airport: 17,
      corporate: 17,
      wedding: 17,
      partyBus: 16,
    },
    description:
      "Second largest city in Illinois with casinos, entertainment, and river walk",
  },
  {
    id: "batavia",
    name: "Batavia",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.85, lng: -88.3126 },
    zipCodes: ["60510"],
    nearbyAirports: { ORD: 26, MDW: 28 },
    applicableServices: {
      airport: 17,
      corporate: 16,
      wedding: 17,
      partyBus: 15,
    },
    description: "Charming Fox River town with historic downtown and windmill",
  },
  {
    id: "geneva",
    name: "Geneva",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.8875, lng: -88.3054 },
    zipCodes: ["60134"],
    nearbyAirports: { ORD: 24, MDW: 28 },
    applicableServices: {
      airport: 17,
      corporate: 17,
      wedding: 18,
      partyBus: 15,
    },
    description:
      "Upscale Fox River town with boutique shopping and Swedish Days festival",
  },
  {
    id: "st-charles",
    name: "St. Charles",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 41.9142, lng: -88.3084 },
    zipCodes: ["60174", "60175"],
    nearbyAirports: { ORD: 22, MDW: 30 },
    applicableServices: {
      airport: 18,
      corporate: 17,
      wedding: 19,
      partyBus: 16,
    },
    description:
      "Picturesque Fox River city with historic Main Street and Scarecrow Festival",
  },
  {
    id: "elgin",
    name: "Elgin",
    state: "IL",
    type: "suburb",
    region: "west",
    coordinates: { lat: 42.0354, lng: -88.2826 },
    zipCodes: ["60120", "60121", "60123"],
    nearbyAirports: { ORD: 20, MDW: 34 },
    applicableServices: {
      airport: 18,
      corporate: 17,
      wedding: 17,
      partyBus: 16,
    },
    description:
      "Diverse city on Fox River with Grand Victoria Casino and cultural events",
  },
];

// SOUTH AND SOUTHWEST SUBURBS (50+)
export const SOUTHERN_SUBURBS: LocationData[] = [
  {
    id: "tinley-park",
    name: "Tinley Park",
    state: "IL",
    type: "suburb",
    region: "south",
    coordinates: { lat: 41.5731, lng: -87.7845 },
    zipCodes: ["60477", "60487"],
    nearbyAirports: { ORD: 28, MDW: 12 },
    applicableServices: {
      airport: 18,
      corporate: 17,
      wedding: 17,
      partyBus: 16,
    },
    description:
      "Large Southwest suburb with convention center and entertainment venues",
  },
  {
    id: "orland-park",
    name: "Orland Park",
    state: "IL",
    type: "suburb",
    region: "south",
    coordinates: { lat: 41.6303, lng: -87.8539 },
    zipCodes: ["60462", "60467"],
    nearbyAirports: { ORD: 26, MDW: 14 },
    applicableServices: {
      airport: 19,
      corporate: 17,
      wedding: 18,
      partyBus: 16,
    },
    description:
      "Affluent Southwest suburb with Orland Square Mall and recreation centers",
  },
  {
    id: "oak-lawn",
    name: "Oak Lawn",
    state: "IL",
    type: "suburb",
    region: "south",
    coordinates: { lat: 41.7195, lng: -87.7479 },
    zipCodes: ["60453"],
    nearbyAirports: { ORD: 20, MDW: 8 },
    applicableServices: {
      airport: 19,
      corporate: 17,
      wedding: 17,
      partyBus: 16,
    },
    description: "Diverse suburb near Midway Airport with shopping and dining",
  },
  {
    id: "evergreen-park",
    name: "Evergreen Park",
    state: "IL",
    type: "suburb",
    region: "south",
    coordinates: { lat: 41.7206, lng: -87.7017 },
    zipCodes: ["60805"],
    nearbyAirports: { ORD: 19, MDW: 8 },
    applicableServices: {
      airport: 19,
      corporate: 16,
      wedding: 16,
      partyBus: 15,
    },
    description: "Residential suburb adjacent to Chicago and near Midway",
  },
  {
    id: "burbank",
    name: "Burbank",
    state: "IL",
    type: "suburb",
    region: "south",
    coordinates: { lat: 41.7339, lng: -87.7695 },
    zipCodes: ["60459"],
    nearbyAirports: { ORD: 18, MDW: 6 },
    applicableServices: {
      airport: 20,
      corporate: 16,
      wedding: 16,
      partyBus: 15,
    },
    description: "Small suburb immediately adjacent to Midway Airport",
  },
  {
    id: "alsip",
    name: "Alsip",
    state: "IL",
    type: "suburb",
    region: "south",
    coordinates: { lat: 41.6689, lng: -87.7384 },
    zipCodes: ["60803"],
    nearbyAirports: { ORD: 21, MDW: 8 },
    applicableServices: {
      airport: 18,
      corporate: 16,
      wedding: 16,
      partyBus: 15,
    },
    description: "South suburb with industrial and residential areas",
  },
  {
    id: "palos-hills",
    name: "Palos Hills",
    state: "IL",
    type: "suburb",
    region: "southwest",
    coordinates: { lat: 41.6978, lng: -87.8173 },
    zipCodes: ["60465"],
    nearbyAirports: { ORD: 22, MDW: 12 },
    applicableServices: {
      airport: 17,
      corporate: 16,
      wedding: 17,
      partyBus: 15,
    },
    description: "Southwest suburb with Moraine Valley Community College",
  },
  {
    id: "palos-heights",
    name: "Palos Heights",
    state: "IL",
    type: "suburb",
    region: "southwest",
    coordinates: { lat: 41.6681, lng: -87.7953 },
    zipCodes: ["60463"],
    nearbyAirports: { ORD: 23, MDW: 12 },
    applicableServices: {
      airport: 17,
      corporate: 16,
      wedding: 17,
      partyBus: 15,
    },
    description: "Family-oriented Southwest suburb with parks",
  },
  {
    id: "palos-park",
    name: "Palos Park",
    state: "IL",
    type: "suburb",
    region: "southwest",
    coordinates: { lat: 41.6675, lng: -87.8387 },
    zipCodes: ["60464"],
    nearbyAirports: { ORD: 24, MDW: 13 },
    applicableServices: {
      airport: 17,
      corporate: 16,
      wedding: 17,
      partyBus: 14,
    },
    description: "Affluent Southwest suburb with nature preserves",
  },
  {
    id: "worth",
    name: "Worth",
    state: "IL",
    type: "suburb",
    region: "south",
    coordinates: { lat: 41.6881, lng: -87.7967 },
    zipCodes: ["60482"],
    nearbyAirports: { ORD: 21, MDW: 10 },
    applicableServices: {
      airport: 18,
      corporate: 16,
      wedding: 16,
      partyBus: 15,
    },
    description: "Small South suburb with residential character",
  },
  {
    id: "oak-forest",
    name: "Oak Forest",
    state: "IL",
    type: "suburb",
    region: "south",
    coordinates: { lat: 41.6025, lng: -87.7439 },
    zipCodes: ["60452"],
    nearbyAirports: { ORD: 26, MDW: 12 },
    applicableServices: {
      airport: 17,
      corporate: 15,
      wedding: 16,
      partyBus: 15,
    },
    description: "South suburb with parks and residential areas",
  },
  {
    id: "midlothian",
    name: "Midlothian",
    state: "IL",
    type: "suburb",
    region: "south",
    coordinates: { lat: 41.6258, lng: -87.7178 },
    zipCodes: ["60445"],
    nearbyAirports: { ORD: 25, MDW: 12 },
    applicableServices: {
      airport: 17,
      corporate: 15,
      wedding: 16,
      partyBus: 15,
    },
    description: "South suburb with Midlothian Meadows",
  },
  {
    id: "crestwood",
    name: "Crestwood",
    state: "IL",
    type: "suburb",
    region: "south",
    coordinates: { lat: 41.6403, lng: -87.7378 },
    zipCodes: ["60445"],
    nearbyAirports: { ORD: 24, MDW: 11 },
    applicableServices: {
      airport: 18,
      corporate: 16,
      wedding: 16,
      partyBus: 15,
    },
    description: "South suburb with residential neighborhoods",
  },
  {
    id: "blue-island",
    name: "Blue Island",
    state: "IL",
    type: "suburb",
    region: "south",
    coordinates: { lat: 41.6572, lng: -87.68 },
    zipCodes: ["60406"],
    nearbyAirports: { ORD: 23, MDW: 10 },
    applicableServices: {
      airport: 17,
      corporate: 15,
      wedding: 16,
      partyBus: 15,
    },
    description: "Historic South suburb with Metra stations",
  },
  {
    id: "calumet-city",
    name: "Calumet City",
    state: "IL",
    type: "suburb",
    region: "south",
    coordinates: { lat: 41.6156, lng: -87.5295 },
    zipCodes: ["60409"],
    nearbyAirports: { ORD: 30, MDW: 16 },
    applicableServices: {
      airport: 16,
      corporate: 14,
      wedding: 15,
      partyBus: 14,
    },
    description: "Industrial South suburb near Indiana border",
  },
  {
    id: "dolton",
    name: "Dolton",
    state: "IL",
    type: "suburb",
    region: "south",
    coordinates: { lat: 41.6389, lng: -87.6073 },
    zipCodes: ["60419"],
    nearbyAirports: { ORD: 28, MDW: 14 },
    applicableServices: {
      airport: 16,
      corporate: 14,
      wedding: 15,
      partyBus: 14,
    },
    description: "South suburb with residential and commercial areas",
  },
  {
    id: "south-holland",
    name: "South Holland",
    state: "IL",
    type: "suburb",
    region: "south",
    coordinates: { lat: 41.6006, lng: -87.6067 },
    zipCodes: ["60473"],
    nearbyAirports: { ORD: 29, MDW: 15 },
    applicableServices: {
      airport: 16,
      corporate: 15,
      wedding: 15,
      partyBus: 14,
    },
    description: "South suburb with parks and recreation",
  },
  {
    id: "harvey",
    name: "Harvey",
    state: "IL",
    type: "suburb",
    region: "south",
    coordinates: { lat: 41.61, lng: -87.6467 },
    zipCodes: ["60426"],
    nearbyAirports: { ORD: 28, MDW: 14 },
    applicableServices: {
      airport: 16,
      corporate: 14,
      wedding: 15,
      partyBus: 14,
    },
    description: "South suburb with Metra station",
  },
  {
    id: "markham",
    name: "Markham",
    state: "IL",
    type: "suburb",
    region: "south",
    coordinates: { lat: 41.5931, lng: -87.6984 },
    zipCodes: ["60428"],
    nearbyAirports: { ORD: 27, MDW: 13 },
    applicableServices: {
      airport: 16,
      corporate: 14,
      wedding: 15,
      partyBus: 14,
    },
    description: "South suburb with residential character",
  },
  {
    id: "hazel-crest",
    name: "Hazel Crest",
    state: "IL",
    type: "suburb",
    region: "south",
    coordinates: { lat: 41.5717, lng: -87.6934 },
    zipCodes: ["60429"],
    nearbyAirports: { ORD: 28, MDW: 14 },
    applicableServices: {
      airport: 16,
      corporate: 14,
      wedding: 15,
      partyBus: 14,
    },
    description: "South suburb with parks and schools",
  },
  {
    id: "homewood",
    name: "Homewood",
    state: "IL",
    type: "suburb",
    region: "south",
    coordinates: { lat: 41.5572, lng: -87.6656 },
    zipCodes: ["60430"],
    nearbyAirports: { ORD: 29, MDW: 15 },
    applicableServices: {
      airport: 17,
      corporate: 16,
      wedding: 16,
      partyBus: 15,
    },
    description: "South suburb with Metra access and downtown area",
  },
  {
    id: "flossmoor",
    name: "Flossmoor",
    state: "IL",
    type: "suburb",
    region: "south",
    coordinates: { lat: 41.5428, lng: -87.6745 },
    zipCodes: ["60422"],
    nearbyAirports: { ORD: 30, MDW: 16 },
    applicableServices: {
      airport: 17,
      corporate: 16,
      wedding: 17,
      partyBus: 15,
    },
    description: "Affluent South suburb with historic train station",
  },
  {
    id: "olympia-fields",
    name: "Olympia Fields",
    state: "IL",
    type: "suburb",
    region: "south",
    coordinates: { lat: 41.5131, lng: -87.6739 },
    zipCodes: ["60461"],
    nearbyAirports: { ORD: 32, MDW: 17 },
    applicableServices: {
      airport: 16,
      corporate: 15,
      wedding: 16,
      partyBus: 14,
    },
    description: "South suburb with golf courses and parks",
  },
  {
    id: "matteson",
    name: "Matteson",
    state: "IL",
    type: "suburb",
    region: "south",
    coordinates: { lat: 41.5039, lng: -87.7131 },
    zipCodes: ["60443"],
    nearbyAirports: { ORD: 30, MDW: 16 },
    applicableServices: {
      airport: 17,
      corporate: 15,
      wedding: 16,
      partyBus: 15,
    },
    description: "South suburb with shopping and entertainment",
  },
  {
    id: "richton-park",
    name: "Richton Park",
    state: "IL",
    type: "suburb",
    region: "south",
    coordinates: { lat: 41.4839, lng: -87.7281 },
    zipCodes: ["60471"],
    nearbyAirports: { ORD: 31, MDW: 17 },
    applicableServices: {
      airport: 16,
      corporate: 14,
      wedding: 15,
      partyBus: 14,
    },
    description: "South suburb with residential areas",
  },
  {
    id: "park-forest",
    name: "Park Forest",
    state: "IL",
    type: "suburb",
    region: "south",
    coordinates: { lat: 41.4842, lng: -87.6745 },
    zipCodes: ["60466"],
    nearbyAirports: { ORD: 32, MDW: 18 },
    applicableServices: {
      airport: 16,
      corporate: 15,
      wedding: 15,
      partyBus: 14,
    },
    description: "Planned community South suburb with arts center",
  },
  {
    id: "chicago-heights",
    name: "Chicago Heights",
    state: "IL",
    type: "suburb",
    region: "south",
    coordinates: { lat: 41.5061, lng: -87.6356 },
    zipCodes: ["60411"],
    nearbyAirports: { ORD: 34, MDW: 19 },
    applicableServices: {
      airport: 15,
      corporate: 14,
      wedding: 15,
      partyBus: 14,
    },
    description: "South suburb with historic downtown",
  },
  {
    id: "country-club-hills",
    name: "Country Club Hills",
    state: "IL",
    type: "suburb",
    region: "south",
    coordinates: { lat: 41.5678, lng: -87.7195 },
    zipCodes: ["60478"],
    nearbyAirports: { ORD: 28, MDW: 14 },
    applicableServices: {
      airport: 16,
      corporate: 15,
      wedding: 15,
      partyBus: 14,
    },
    description: "South suburb with golf courses",
  },
  {
    id: "mokena",
    name: "Mokena",
    state: "IL",
    type: "suburb",
    region: "southwest",
    coordinates: { lat: 41.5261, lng: -87.8806 },
    zipCodes: ["60448"],
    nearbyAirports: { ORD: 32, MDW: 18 },
    applicableServices: {
      airport: 17,
      corporate: 15,
      wedding: 16,
      partyBus: 15,
    },
    description: "Growing Southwest suburb with downtown area",
  },
  {
    id: "frankfort",
    name: "Frankfort",
    state: "IL",
    type: "suburb",
    region: "southwest",
    coordinates: { lat: 41.4959, lng: -87.8489 },
    zipCodes: ["60423"],
    nearbyAirports: { ORD: 34, MDW: 20 },
    applicableServices: {
      airport: 17,
      corporate: 15,
      wedding: 17,
      partyBus: 15,
    },
    description: "Southwest suburb with historic Old Plank Road Trail",
  },
  {
    id: "new-lenox",
    name: "New Lenox",
    state: "IL",
    type: "suburb",
    region: "southwest",
    coordinates: { lat: 41.5117, lng: -87.9656 },
    zipCodes: ["60451"],
    nearbyAirports: { ORD: 34, MDW: 22 },
    applicableServices: {
      airport: 16,
      corporate: 15,
      wedding: 16,
      partyBus: 15,
    },
    description: "Fast-growing Southwest suburb with parks and trails",
  },
  {
    id: "joliet",
    name: "Joliet",
    state: "IL",
    type: "suburb",
    region: "southwest",
    coordinates: { lat: 41.525, lng: -88.0817 },
    zipCodes: ["60431", "60432", "60433", "60435"],
    nearbyAirports: { ORD: 38, MDW: 26 },
    applicableServices: {
      airport: 17,
      corporate: 16,
      wedding: 17,
      partyBus: 16,
    },
    description: "Third largest city in Illinois with casinos and motorsports",
  },
  {
    id: "shorewood",
    name: "Shorewood",
    state: "IL",
    type: "suburb",
    region: "southwest",
    coordinates: { lat: 41.52, lng: -88.202 },
    zipCodes: ["60404"],
    nearbyAirports: { ORD: 40, MDW: 28 },
    applicableServices: {
      airport: 16,
      corporate: 15,
      wedding: 16,
      partyBus: 14,
    },
    description: "Growing Southwest suburb along Des Plaines River",
  },
  {
    id: "crest-hill",
    name: "Crest Hill",
    state: "IL",
    type: "suburb",
    region: "southwest",
    coordinates: { lat: 41.555, lng: -88.0989 },
    zipCodes: ["60403"],
    nearbyAirports: { ORD: 36, MDW: 25 },
    applicableServices: {
      airport: 16,
      corporate: 15,
      wedding: 15,
      partyBus: 14,
    },
    description: "Southwest suburb with shopping centers",
  },
  {
    id: "lansing",
    name: "Lansing",
    state: "IL",
    type: "suburb",
    region: "south",
    coordinates: { lat: 41.5647, lng: -87.5389 },
    zipCodes: ["60438"],
    nearbyAirports: { ORD: 32, MDW: 18 },
    applicableServices: {
      airport: 16,
      corporate: 14,
      wedding: 15,
      partyBus: 14,
    },
    description: "South suburb near Indiana border with shopping",
  },
  {
    id: "munster-in",
    name: "Munster",
    state: "IN",
    type: "suburb",
    region: "south",
    coordinates: { lat: 41.5645, lng: -87.5125 },
    zipCodes: ["46321"],
    nearbyAirports: { ORD: 34, MDW: 20 },
    applicableServices: {
      airport: 16,
      corporate: 15,
      wedding: 15,
      partyBus: 14,
    },
    description:
      "Indiana suburb serving Chicago metro area with shopping and dining",
  },
  {
    id: "hammond-in",
    name: "Hammond",
    state: "IN",
    type: "suburb",
    region: "south",
    coordinates: { lat: 41.5833, lng: -87.5 },
    zipCodes: ["46320", "46323"],
    nearbyAirports: { ORD: 32, MDW: 19 },
    applicableServices: {
      airport: 16,
      corporate: 15,
      wedding: 15,
      partyBus: 15,
    },
    description: "Indiana city bordering Chicago with Horseshoe Casino",
  },
];
