/**
 * Location Expansion Script
 * Expands Chicago locations from 25 to 173+ covering all neighborhoods and suburbs
 */

import * as admin from 'firebase-admin';

const db = admin.firestore();

interface LocationData {
  id: string;
  name: string;
  state: string;
  type: 'neighborhood' | 'suburb';
  region: 'downtown' | 'north' | 'west' | 'south' | 'southwest';
  coordinates: { lat: number; lng: number };
  zipCodes: string[];
  nearbyAirports: {
    ORD: number; // distance in miles
    MDW: number;
  };
  applicableServices: {
    airport?: number;
    corporate?: number;
    wedding?: number;
    partyBus?: number;
  };
  description: string;
}

// CHICAGO NEIGHBORHOODS (77 official neighborhoods)
const CHICAGO_NEIGHBORHOODS: LocationData[] = [
  // DOWNTOWN & NEAR NORTH (Loop, River North, etc.)
  { id: 'loop', name: 'Loop', state: 'IL', type: 'neighborhood', region: 'downtown', coordinates: { lat: 41.8819, lng: -87.6278 }, zipCodes: ['60601', '60602', '60603'], nearbyAirports: { ORD: 18, MDW: 11 }, applicableServices: { airport: 20, corporate: 20, wedding: 18, partyBus: 16 }, description: 'Chicago\'s central business district with iconic skyscrapers and world-class dining' },
  { id: 'river-north', name: 'River North', state: 'IL', type: 'neighborhood', region: 'downtown', coordinates: { lat: 41.8888, lng: -87.6233 }, zipCodes: ['60610', '60654'], nearbyAirports: { ORD: 17, MDW: 12 }, applicableServices: { airport: 20, corporate: 20, wedding: 20, partyBus: 19 }, description: 'Premier dining and nightlife destination with art galleries and converted lofts' },
  { id: 'gold-coast', name: 'Gold Coast', state: 'IL', type: 'neighborhood', region: 'downtown', coordinates: { lat: 41.8979, lng: -87.6243 }, zipCodes: ['60611'], nearbyAirports: { ORD: 19, MDW: 13 }, applicableServices: { airport: 20, corporate: 20, wedding: 20, partyBus: 15 }, description: 'Upscale lakefront neighborhood with historic mansions and luxury shopping' },
  { id: 'streeterville', name: 'Streeterville', state: 'IL', type: 'neighborhood', region: 'downtown', coordinates: { lat: 41.8926, lng: -87.6189 }, zipCodes: ['60611'], nearbyAirports: { ORD: 18, MDW: 13 }, applicableServices: { airport: 19, corporate: 19, wedding: 18, partyBus: 16 }, description: 'Dense neighborhood near Navy Pier with hotels, medical facilities, and lakefront access' },
  { id: 'near-north-side', name: 'Near North Side', state: 'IL', type: 'neighborhood', region: 'downtown', coordinates: { lat: 41.9025, lng: -87.6313 }, zipCodes: ['60610', '60611'], nearbyAirports: { ORD: 18, MDW: 13 }, applicableServices: { airport: 19, corporate: 19, wedding: 18, partyBus: 17 }, description: 'Mixed-use area combining residential, commercial, and entertainment venues' },
  { id: 'near-south-side', name: 'Near South Side', state: 'IL', type: 'neighborhood', region: 'south', coordinates: { lat: 41.8555, lng: -87.6233 }, zipCodes: ['60605', '60616'], nearbyAirports: { ORD: 19, MDW: 9 }, applicableServices: { airport: 18, corporate: 17, wedding: 16, partyBus: 15 }, description: 'Historic area undergoing revitalization near McCormick Place' },
  { id: 'near-west-side', name: 'Near West Side', state: 'IL', type: 'neighborhood', region: 'west', coordinates: { lat: 41.8796, lng: -87.6550 }, zipCodes: ['60607', '60612'], nearbyAirports: { ORD: 16, MDW: 11 }, applicableServices: { airport: 18, corporate: 18, wedding: 17, partyBus: 16 }, description: 'Diverse neighborhood with UIC campus, medical district, and historic Greektown' },
  { id: 'west-loop', name: 'West Loop', state: 'IL', type: 'neighborhood', region: 'downtown', coordinates: { lat: 41.8845, lng: -87.6425 }, zipCodes: ['60607', '60661'], nearbyAirports: { ORD: 16, MDW: 11 }, applicableServices: { airport: 20, corporate: 20, wedding: 19, partyBus: 18 }, description: 'Trendy neighborhood known for top restaurants, tech companies, and loft conversions' },
  { id: 'south-loop', name: 'South Loop', state: 'IL', type: 'neighborhood', region: 'downtown', coordinates: { lat: 41.8672, lng: -87.6266 }, zipCodes: ['60604', '60605'], nearbyAirports: { ORD: 19, MDW: 10 }, applicableServices: { airport: 19, corporate: 18, wedding: 18, partyBus: 16 }, description: 'Residential area with museums, parks, and Grant Park proximity' },

  // NORTH SIDE NEIGHBORHOODS
  { id: 'lincoln-park', name: 'Lincoln Park', state: 'IL', type: 'neighborhood', region: 'north', coordinates: { lat: 41.9148, lng: -87.6334 }, zipCodes: ['60614', '60610'], nearbyAirports: { ORD: 20, MDW: 15 }, applicableServices: { airport: 20, corporate: 18, wedding: 20, partyBus: 18 }, description: 'Upscale neighborhood with Lincoln Park Zoo, lakefront parks, and vibrant nightlife' },
  { id: 'lakeview', name: 'Lakeview', state: 'IL', type: 'neighborhood', region: 'north', coordinates: { lat: 41.9478, lng: -87.6555 }, zipCodes: ['60613', '60657'], nearbyAirports: { ORD: 22, MDW: 17 }, applicableServices: { airport: 19, corporate: 16, wedding: 17, partyBus: 20 }, description: 'Home to Wrigley Field with diverse entertainment, restaurants, and Boystown' },
  { id: 'wrigleyville', name: 'Wrigleyville', state: 'IL', type: 'neighborhood', region: 'north', coordinates: { lat: 41.9480, lng: -87.6557 }, zipCodes: ['60613'], nearbyAirports: { ORD: 22, MDW: 17 }, applicableServices: { airport: 18, corporate: 15, wedding: 16, partyBus: 20 }, description: 'Sports and entertainment district surrounding Wrigley Field' },
  { id: 'uptown', name: 'Uptown', state: 'IL', type: 'neighborhood', region: 'north', coordinates: { lat: 41.9661, lng: -87.6551 }, zipCodes: ['60640', '60613'], nearbyAirports: { ORD: 24, MDW: 19 }, applicableServices: { airport: 17, corporate: 15, wedding: 16, partyBus: 18 }, description: 'Culturally diverse neighborhood with historic theaters and entertainment venues' },
  { id: 'andersonville', name: 'Andersonville', state: 'IL', type: 'neighborhood', region: 'north', coordinates: { lat: 41.9794, lng: -87.6689 }, zipCodes: ['60640'], nearbyAirports: { ORD: 24, MDW: 20 }, applicableServices: { airport: 17, corporate: 15, wedding: 17, partyBus: 17 }, description: 'Charming neighborhood with Swedish heritage, boutiques, and diverse dining' },
  { id: 'edgewater', name: 'Edgewater', state: 'IL', type: 'neighborhood', region: 'north', coordinates: { lat: 41.9803, lng: -87.6623 }, zipCodes: ['60640', '60660'], nearbyAirports: { ORD: 24, MDW: 20 }, applicableServices: { airport: 17, corporate: 15, wedding: 16, partyBus: 16 }, description: 'Lakefront neighborhood with diverse population and architectural gems' },
  { id: 'rogers-park', name: 'Rogers Park', state: 'IL', type: 'neighborhood', region: 'north', coordinates: { lat: 42.0084, lng: -87.6686 }, zipCodes: ['60626', '60660'], nearbyAirports: { ORD: 26, MDW: 22 }, applicableServices: { airport: 16, corporate: 14, wedding: 15, partyBus: 15 }, description: 'Diverse lakefront neighborhood with Loyola University and beaches' },
  { id: 'west-ridge', name: 'West Ridge', state: 'IL', type: 'neighborhood', region: 'north', coordinates: { lat: 42.0150, lng: -87.6931 }, zipCodes: ['60645', '60659'], nearbyAirports: { ORD: 24, MDW: 23 }, applicableServices: { airport: 16, corporate: 14, wedding: 15, partyBus: 14 }, description: 'Residential neighborhood with diverse communities and family-friendly atmosphere' },
  { id: 'lincoln-square', name: 'Lincoln Square', state: 'IL', type: 'neighborhood', region: 'north', coordinates: { lat: 41.9701, lng: -87.6916 }, zipCodes: ['60625'], nearbyAirports: { ORD: 22, MDW: 20 }, applicableServices: { airport: 17, corporate: 15, wedding: 17, partyBus: 16 }, description: 'European-style neighborhood with German heritage, boutiques, and Old Town School of Folk Music' },
  { id: 'north-center', name: 'North Center', state: 'IL', type: 'neighborhood', region: 'north', coordinates: { lat: 41.9542, lng: -87.6777 }, zipCodes: ['60618'], nearbyAirports: { ORD: 21, MDW: 18 }, applicableServices: { airport: 17, corporate: 16, wedding: 17, partyBus: 16 }, description: 'Family-friendly neighborhood with tree-lined streets and local businesses' },
  { id: 'ravenswood', name: 'Ravenswood', state: 'IL', type: 'neighborhood', region: 'north', coordinates: { lat: 41.9638, lng: -87.6744 }, zipCodes: ['60640', '60625'], nearbyAirports: { ORD: 22, MDW: 19 }, applicableServices: { airport: 17, corporate: 15, wedding: 16, partyBus: 16 }, description: 'Artistic neighborhood with breweries, music venues, and industrial character' },

  // WEST SIDE NEIGHBORHOODS
  { id: 'wicker-park', name: 'Wicker Park', state: 'IL', type: 'neighborhood', region: 'west', coordinates: { lat: 41.9083, lng: -87.6850 }, zipCodes: ['60622'], nearbyAirports: { ORD: 18, MDW: 14 }, applicableServices: { airport: 18, corporate: 16, wedding: 18, partyBus: 20 }, description: 'Trendy neighborhood with art, music, nightlife, and independent shops' },
  { id: 'bucktown', name: 'Bucktown', state: 'IL', type: 'neighborhood', region: 'west', coordinates: { lat: 41.9256, lng: -87.6802 }, zipCodes: ['60647'], nearbyAirports: { ORD: 19, MDW: 15 }, applicableServices: { airport: 18, corporate: 16, wedding: 18, partyBus: 19 }, description: 'Hip neighborhood adjacent to Wicker Park with boutiques and restaurants' },
  { id: 'logan-square', name: 'Logan Square', state: 'IL', type: 'neighborhood', region: 'west', coordinates: { lat: 41.9277, lng: -87.7022 }, zipCodes: ['60647'], nearbyAirports: { ORD: 17, MDW: 16 }, applicableServices: { airport: 17, corporate: 15, wedding: 17, partyBus: 19 }, description: 'Diverse neighborhood with boulevards, cocktail bars, and artistic community' },
  { id: 'humboldt-park', name: 'Humboldt Park', state: 'IL', type: 'neighborhood', region: 'west', coordinates: { lat: 41.9057, lng: -87.7018 }, zipCodes: ['60622', '60647'], nearbyAirports: { ORD: 16, MDW: 14 }, applicableServices: { airport: 16, corporate: 14, wedding: 15, partyBus: 17 }, description: 'Large park area with Puerto Rican culture, lagoons, and community events' },
  { id: 'avondale', name: 'Avondale', state: 'IL', type: 'neighborhood', region: 'west', coordinates: { lat: 41.9394, lng: -87.7106 }, zipCodes: ['60618'], nearbyAirports: { ORD: 16, MDW: 17 }, applicableServices: { airport: 16, corporate: 14, wedding: 15, partyBus: 16 }, description: 'Residential neighborhood with Polish heritage and growing restaurant scene' },
  { id: 'hermosa', name: 'Hermosa', state: 'IL', type: 'neighborhood', region: 'west', coordinates: { lat: 41.9156, lng: -87.7237 }, zipCodes: ['60639'], nearbyAirports: { ORD: 14, MDW: 16 }, applicableServices: { airport: 15, corporate: 13, wedding: 14, partyBus: 15 }, description: 'Working-class neighborhood with strong community ties and parks' },
  { id: 'belmont-cragin', name: 'Belmont Cragin', state: 'IL', type: 'neighborhood', region: 'west', coordinates: { lat: 41.9329, lng: -87.7631 }, zipCodes: ['60639', '60707'], nearbyAirports: { ORD: 10, MDW: 18 }, applicableServices: { airport: 17, corporate: 14, wedding: 14, partyBus: 15 }, description: 'Residential area near O\'Hare with diverse population' },
  { id: 'austin', name: 'Austin', state: 'IL', type: 'neighborhood', region: 'west', coordinates: { lat: 41.8969, lng: -87.7644 }, zipCodes: ['60644', '60651'], nearbyAirports: { ORD: 13, MDW: 15 }, applicableServices: { airport: 15, corporate: 13, wedding: 13, partyBus: 14 }, description: 'Large West Side neighborhood with historic architecture' },
  { id: 'garfield-park', name: 'Garfield Park', state: 'IL', type: 'neighborhood', region: 'west', coordinates: { lat: 41.8804, lng: -87.7166 }, zipCodes: ['60624', '60612'], nearbyAirports: { ORD: 14, MDW: 13 }, applicableServices: { airport: 15, corporate: 13, wedding: 14, partyBus: 14 }, description: 'West Side neighborhood home to Garfield Park Conservatory' },
  { id: 'west-town', name: 'West Town', state: 'IL', type: 'neighborhood', region: 'west', coordinates: { lat: 41.8959, lng: -87.6739 }, zipCodes: ['60622', '60642'], nearbyAirports: { ORD: 17, MDW: 13 }, applicableServices: { airport: 18, corporate: 17, wedding: 17, partyBus: 18 }, description: 'Encompasses Ukrainian Village, Noble Square with restaurants and nightlife' },
  { id: 'ukrainian-village', name: 'Ukrainian Village', state: 'IL', type: 'neighborhood', region: 'west', coordinates: { lat: 41.8994, lng: -87.6773 }, zipCodes: ['60622'], nearbyAirports: { ORD: 17, MDW: 13 }, applicableServices: { airport: 17, corporate: 16, wedding: 17, partyBus: 17 }, description: 'Historic neighborhood with Ukrainian heritage and trendy restaurants' },
  { id: 'noble-square', name: 'Noble Square', state: 'IL', type: 'neighborhood', region: 'west', coordinates: { lat: 41.8977, lng: -87.6631 }, zipCodes: ['60642'], nearbyAirports: { ORD: 17, MDW: 12 }, applicableServices: { airport: 17, corporate: 16, wedding: 16, partyBus: 17 }, description: 'Emerging neighborhood between River North and Wicker Park' },
  { id: 'east-garfield-park', name: 'East Garfield Park', state: 'IL', type: 'neighborhood', region: 'west', coordinates: { lat: 41.8808, lng: -87.7015 }, zipCodes: ['60612'], nearbyAirports: { ORD: 15, MDW: 13 }, applicableServices: { airport: 15, corporate: 13, wedding: 13, partyBus: 14 }, description: 'Historic West Side community with ongoing revitalization efforts' },

  // SOUTH SIDE NEIGHBORHOODS
  { id: 'bridgeport', name: 'Bridgeport', state: 'IL', type: 'neighborhood', region: 'south', coordinates: { lat: 41.8369, lng: -87.6448 }, zipCodes: ['60608', '60609'], nearbyAirports: { ORD: 20, MDW: 8 }, applicableServices: { airport: 17, corporate: 15, wedding: 16, partyBus: 16 }, description: 'Historic neighborhood near Guaranteed Rate Field with strong Irish and Chinese communities' },
  { id: 'pilsen', name: 'Pilsen', state: 'IL', type: 'neighborhood', region: 'south', coordinates: { lat: 41.8585, lng: -87.6772 }, zipCodes: ['60608'], nearbyAirports: { ORD: 18, MDW: 10 }, applicableServices: { airport: 17, corporate: 15, wedding: 16, partyBus: 17 }, description: 'Vibrant Mexican-American neighborhood with murals, art galleries, and authentic cuisine' },
  { id: 'little-village', name: 'Little Village', state: 'IL', type: 'neighborhood', region: 'southwest', coordinates: { lat: 41.8509, lng: -87.7168 }, zipCodes: ['60623'], nearbyAirports: { ORD: 16, MDW: 10 }, applicableServices: { airport: 16, corporate: 14, wedding: 15, partyBus: 16 }, description: 'Predominantly Mexican neighborhood known as the "Mexico of the Midwest"' },
  { id: 'hyde-park', name: 'Hyde Park', state: 'IL', type: 'neighborhood', region: 'south', coordinates: { lat: 41.7943, lng: -87.5960 }, zipCodes: ['60615', '60637'], nearbyAirports: { ORD: 24, MDW: 11 }, applicableServices: { airport: 17, corporate: 16, wedding: 17, partyBus: 15 }, description: 'Intellectual hub home to University of Chicago, museums, and Obama\'s residence' },
  { id: 'kenwood', name: 'Kenwood', state: 'IL', type: 'neighborhood', region: 'south', coordinates: { lat: 41.8081, lng: -87.5952 }, zipCodes: ['60615', '60653'], nearbyAirports: { ORD: 23, MDW: 11 }, applicableServices: { airport: 17, corporate: 16, wedding: 17, partyBus: 15 }, description: 'Historic neighborhood with grand mansions and proximity to lakefront' },
  { id: 'woodlawn', name: 'Woodlawn', state: 'IL', type: 'neighborhood', region: 'south', coordinates: { lat: 41.7807, lng: -87.5966 }, zipCodes: ['60637', '60615'], nearbyAirports: { ORD: 25, MDW: 12 }, applicableServices: { airport: 16, corporate: 14, wedding: 15, partyBus: 14 }, description: 'South Side neighborhood undergoing revitalization near University of Chicago' },
  { id: 'south-shore', name: 'South Shore', state: 'IL', type: 'neighborhood', region: 'south', coordinates: { lat: 41.7596, lng: -87.5710 }, zipCodes: ['60649'], nearbyAirports: { ORD: 26, MDW: 14 }, applicableServices: { airport: 15, corporate: 13, wedding: 14, partyBus: 14 }, description: 'Lakefront neighborhood with beaches, cultural center, and historic architecture' },
  { id: 'bronzeville', name: 'Bronzeville', state: 'IL', type: 'neighborhood', region: 'south', coordinates: { lat: 41.8181, lng: -87.6163 }, zipCodes: ['60616', '60653'], nearbyAirports: { ORD: 22, MDW: 10 }, applicableServices: { airport: 16, corporate: 15, wedding: 16, partyBus: 15 }, description: 'Historic African-American neighborhood with rich jazz and blues heritage' },
  { id: 'chinatown', name: 'Chinatown', state: 'IL', type: 'neighborhood', region: 'south', coordinates: { lat: 41.8518, lng: -87.6318 }, zipCodes: ['60616'], nearbyAirports: { ORD: 20, MDW: 9 }, applicableServices: { airport: 17, corporate: 15, wedding: 17, partyBus: 16 }, description: 'Vibrant Asian community with authentic restaurants, shops, and cultural events' },
  { id: 'back-of-the-yards', name: 'Back of the Yards', state: 'IL', type: 'neighborhood', region: 'south', coordinates: { lat: 41.8117, lng: -87.6601 }, zipCodes: ['60609'], nearbyAirports: { ORD: 19, MDW: 9 }, applicableServices: { airport: 15, corporate: 13, wedding: 14, partyBus: 14 }, description: 'Historic stockyard neighborhood with strong community organizations' },
  { id: 'brighton-park', name: 'Brighton Park', state: 'IL', type: 'neighborhood', region: 'southwest', coordinates: { lat: 41.8187, lng: -87.7007 }, zipCodes: ['60632'], nearbyAirports: { ORD: 16, MDW: 7 }, applicableServices: { airport: 16, corporate: 14, wedding: 15, partyBus: 15 }, description: 'Southwest Side neighborhood near Midway Airport with diverse population' },
  { id: 'mckinley-park', name: 'McKinley Park', state: 'IL', type: 'neighborhood', region: 'south', coordinates: { lat: 41.8300, lng: -87.6731 }, zipCodes: ['60609'], nearbyAirports: { ORD: 18, MDW: 8 }, applicableServices: { airport: 16, corporate: 14, wedding: 15, partyBus: 15 }, description: 'Family-oriented neighborhood with parks and lagoons' },
  { id: 'new-city', name: 'New City', state: 'IL', type: 'neighborhood', region: 'south', coordinates: { lat: 41.8066, lng: -87.6532 }, zipCodes: ['60609'], nearbyAirports: { ORD: 19, MDW: 8 }, applicableServices: { airport: 15, corporate: 13, wedding: 14, partyBus: 14 }, description: 'Southwest Side neighborhood including Canaryville' },
  { id: 'englewood', name: 'Englewood', state: 'IL', type: 'neighborhood', region: 'south', coordinates: { lat: 41.7795, lng: -87.6476 }, zipCodes: ['60621'], nearbyAirports: { ORD: 21, MDW: 8 }, applicableServices: { airport: 14, corporate: 12, wedding: 13, partyBus: 13 }, description: 'South Side community with transit hub and ongoing development' },
  { id: 'west-englewood', name: 'West Englewood', state: 'IL', type: 'neighborhood', region: 'south', coordinates: { lat: 41.7758, lng: -87.6657 }, zipCodes: ['60636'], nearbyAirports: { ORD: 20, MDW: 8 }, applicableServices: { airport: 14, corporate: 12, wedding: 13, partyBus: 13 }, description: 'Southwest Side neighborhood with community initiatives' },
  { id: 'greater-grand-crossing', name: 'Greater Grand Crossing', state: 'IL', type: 'neighborhood', region: 'south', coordinates: { lat: 41.7659, lng: -87.6166 }, zipCodes: ['60619'], nearbyAirports: { ORD: 24, MDW: 11 }, applicableServices: { airport: 15, corporate: 13, wedding: 14, partyBus: 13 }, description: 'South Side neighborhood with parks and community programs' },
  { id: 'chatham', name: 'Chatham', state: 'IL', type: 'neighborhood', region: 'south', coordinates: { lat: 41.7332, lng: -87.6157 }, zipCodes: ['60619'], nearbyAirports: { ORD: 26, MDW: 12 }, applicableServices: { airport: 15, corporate: 13, wedding: 14, partyBus: 13 }, description: 'Predominantly African-American middle-class neighborhood' },
  { id: 'auburn-gresham', name: 'Auburn Gresham', state: 'IL', type: 'neighborhood', region: 'south', coordinates: { lat: 41.7407, lng: -87.6537 }, zipCodes: ['60620'], nearbyAirports: { ORD: 24, MDW: 10 }, applicableServices: { airport: 15, corporate: 13, wedding: 14, partyBus: 13 }, description: 'South Side neighborhood with historic homes and churches' },
  { id: 'beverly', name: 'Beverly', state: 'IL', type: 'neighborhood', region: 'south', coordinates: { lat: 41.7214, lng: -87.6769 }, zipCodes: ['60643'], nearbyAirports: { ORD: 24, MDW: 11 }, applicableServices: { airport: 16, corporate: 15, wedding: 16, partyBus: 14 }, description: 'Affluent South Side neighborhood with hills and historic homes' },
  { id: 'mount-greenwood', name: 'Mount Greenwood', state: 'IL', type: 'neighborhood', region: 'south', coordinates: { lat: 41.6945, lng: -87.7067 }, zipCodes: ['60655'], nearbyAirports: { ORD: 25, MDW: 11 }, applicableServices: { airport: 16, corporate: 14, wedding: 15, partyBus: 14 }, description: 'Far South Side neighborhood with strong Irish heritage' },
  { id: 'morgan-park', name: 'Morgan Park', state: 'IL', type: 'neighborhood', region: 'south', coordinates: { lat: 41.6915, lng: -87.6763 }, zipCodes: ['60643'], nearbyAirports: { ORD: 26, MDW: 12 }, applicableServices: { airport: 15, corporate: 14, wedding: 15, partyBus: 13 }, description: 'Historic South Side neighborhood with Victorian architecture' },
  { id: 'washington-heights', name: 'Washington Heights', state: 'IL', type: 'neighborhood', region: 'south', coordinates: { lat: 41.7152, lng: -87.6513 }, zipCodes: ['60643'], nearbyAirports: { ORD: 26, MDW: 11 }, applicableServices: { airport: 15, corporate: 14, wedding: 14, partyBus: 13 }, description: 'Residential South Side neighborhood with parks and churches' },
  { id: 'roseland', name: 'Roseland', state: 'IL', type: 'neighborhood', region: 'south', coordinates: { lat: 41.6926, lng: -87.6157 }, zipCodes: ['60628'], nearbyAirports: { ORD: 28, MDW: 14 }, applicableServices: { airport: 14, corporate: 12, wedding: 13, partyBus: 12 }, description: 'Far South Side neighborhood with historic commercial district' },
  { id: 'pullman', name: 'Pullman', state: 'IL', type: 'neighborhood', region: 'south', coordinates: { lat: 41.7075, lng: -87.6089 }, zipCodes: ['60628'], nearbyAirports: { ORD: 29, MDW: 15 }, applicableServices: { airport: 14, corporate: 13, wedding: 14, partyBus: 12 }, description: 'Historic planned industrial community, now a National Monument' },
  { id: 'west-pullman', name: 'West Pullman', state: 'IL', type: 'neighborhood', region: 'south', coordinates: { lat: 41.7131, lng: -87.6427 }, zipCodes: ['60628'], nearbyAirports: { ORD: 28, MDW: 13 }, applicableServices: { airport: 14, corporate: 12, wedding: 13, partyBus: 12 }, description: 'South Side neighborhood with parks and community centers' },
  { id: 'riverdale', name: 'Riverdale', state: 'IL', type: 'neighborhood', region: 'south', coordinates: { lat: 41.6433, lng: -87.6320 }, zipCodes: ['60827'], nearbyAirports: { ORD: 31, MDW: 16 }, applicableServices: { airport: 13, corporate: 11, wedding: 12, partyBus: 11 }, description: 'Far South Side neighborhood near Indiana border' },
  { id: 'hegewisch', name: 'Hegewisch', state: 'IL', type: 'neighborhood', region: 'south', coordinates: { lat: 41.6594, lng: -87.5457 }, zipCodes: ['60633'], nearbyAirports: { ORD: 34, MDW: 19 }, applicableServices: { airport: 13, corporate: 11, wedding: 12, partyBus: 11 }, description: 'Industrial far Southeast Side neighborhood' },
  { id: 'south-deering', name: 'South Deering', state: 'IL', type: 'neighborhood', region: 'south', coordinates: { lat: 41.6920, lng: -87.5409 }, zipCodes: ['60617'], nearbyAirports: { ORD: 32, MDW: 17 }, applicableServices: { airport: 13, corporate: 11, wedding: 12, partyBus: 11 }, description: 'Southeast Side neighborhood near Lake Calumet' },
  { id: 'east-side', name: 'East Side', state: 'IL', type: 'neighborhood', region: 'south', coordinates: { lat: 41.7110, lng: -87.5431 }, zipCodes: ['60617'], nearbyAirports: { ORD: 31, MDW: 16 }, applicableServices: { airport: 14, corporate: 12, wedding: 13, partyBus: 12 }, description: 'Southeast Side industrial neighborhood with lakefront access' },
  { id: 'south-chicago', name: 'South Chicago', state: 'IL', type: 'neighborhood', region: 'south', coordinates: { lat: 41.7390, lng: -87.5546 }, zipCodes: ['60617'], nearbyAirports: { ORD: 30, MDW: 15 }, applicableServices: { airport: 14, corporate: 12, wedding: 13, partyBus: 12 }, description: 'Historic steel industry neighborhood with lakefront parks' },
  { id: 'gage-park', name: 'Gage Park', state: 'IL', type: 'neighborhood', region: 'southwest', coordinates: { lat: 41.7944, lng: -87.6946 }, zipCodes: ['60629'], nearbyAirports: { ORD: 19, MDW: 7 }, applicableServices: { airport: 15, corporate: 13, wedding: 14, partyBus: 14 }, description: 'Southwest Side neighborhood near Midway Airport' },
  { id: 'west-lawn', name: 'West Lawn', state: 'IL', type: 'neighborhood', region: 'southwest', coordinates: { lat: 41.7726, lng: -87.7201 }, zipCodes: ['60629'], nearbyAirports: { ORD: 18, MDW: 6 }, applicableServices: { airport: 16, corporate: 14, wedding: 14, partyBus: 14 }, description: 'Southwest Side neighborhood adjacent to Midway Airport' },
  { id: 'chicago-lawn', name: 'Chicago Lawn', state: 'IL', type: 'neighborhood', region: 'southwest', coordinates: { lat: 41.7724, lng: -87.6946 }, zipCodes: ['60629'], nearbyAirports: { ORD: 19, MDW: 7 }, applicableServices: { airport: 15, corporate: 13, wedding: 14, partyBus: 13 }, description: 'Southwest Side neighborhood with Marquette Park' },
  { id: 'west-elsdon', name: 'West Elsdon', state: 'IL', type: 'neighborhood', region: 'southwest', coordinates: { lat: 41.7944, lng: -87.7201 }, zipCodes: ['60632'], nearbyAirports: { ORD: 17, MDW: 6 }, applicableServices: { airport: 16, corporate: 14, wedding: 14, partyBus: 14 }, description: 'Southwest Side neighborhood near Midway Airport' },
  { id: 'archer-heights', name: 'Archer Heights', state: 'IL', type: 'neighborhood', region: 'southwest', coordinates: { lat: 41.8092, lng: -87.7269 }, zipCodes: ['60632'], nearbyAirports: { ORD: 16, MDW: 7 }, applicableServices: { airport: 16, corporate: 14, wedding: 14, partyBus: 14 }, description: 'Southwest Side residential neighborhood' },
  { id: 'clearing', name: 'Clearing', state: 'IL', type: 'neighborhood', region: 'southwest', coordinates: { lat: 41.7874, lng: -87.7625 }, zipCodes: ['60638'], nearbyAirports: { ORD: 14, MDW: 5 }, applicableServices: { airport: 18, corporate: 14, wedding: 14, partyBus: 14 }, description: 'Southwest Side neighborhood immediately adjacent to Midway Airport' },
  { id: 'garfield-ridge', name: 'Garfield Ridge', state: 'IL', type: 'neighborhood', region: 'southwest', coordinates: { lat: 41.7874, lng: -87.7625 }, zipCodes: ['60638'], nearbyAirports: { ORD: 13, MDW: 5 }, applicableServices: { airport: 18, corporate: 14, wedding: 14, partyBus: 13 }, description: 'Southwest Side neighborhood bordering Midway Airport' },
  { id: 'ashburn', name: 'Ashburn', state: 'IL', type: 'neighborhood', region: 'southwest', coordinates: { lat: 41.7434, lng: -87.7093 }, zipCodes: ['60652'], nearbyAirports: { ORD: 21, MDW: 9 }, applicableServices: { airport: 15, corporate: 13, wedding: 14, partyBus: 13 }, description: 'Large Southwest Side neighborhood with diverse population' },

  // ADDITIONAL KEY CHICAGO NEIGHBORHOODS
  { id: 'old-town', name: 'Old Town', state: 'IL', type: 'neighborhood', region: 'north', coordinates: { lat: 41.9087, lng: -87.6377 }, zipCodes: ['60610', '60614'], nearbyAirports: { ORD: 19, MDW: 14 }, applicableServices: { airport: 19, corporate: 17, wedding: 18, partyBus: 18 }, description: 'Historic neighborhood with Victorian homes, comedy clubs, and dining' },
  { id: 'portage-park', name: 'Portage Park', state: 'IL', type: 'neighborhood', region: 'north', coordinates: { lat: 41.9554, lng: -87.7644 }, zipCodes: ['60634'], nearbyAirports: { ORD: 10, MDW: 18 }, applicableServices: { airport: 17, corporate: 14, wedding: 15, partyBus: 15 }, description: 'Northwest Side neighborhood with large park and Polish community' },
  { id: 'jefferson-park', name: 'Jefferson Park', state: 'IL', type: 'neighborhood', region: 'north', coordinates: { lat: 41.9705, lng: -87.7611 }, zipCodes: ['60630'], nearbyAirports: { ORD: 8, MDW: 19 }, applicableServices: { airport: 18, corporate: 14, wedding: 15, partyBus: 15 }, description: 'Northwest Side transit hub near O\'Hare Airport' },
  { id: 'forest-glen', name: 'Forest Glen', state: 'IL', type: 'neighborhood', region: 'north', coordinates: { lat: 41.9784, lng: -87.7550 }, zipCodes: ['60630'], nearbyAirports: { ORD: 8, MDW: 20 }, applicableServices: { airport: 17, corporate: 14, wedding: 15, partyBus: 14 }, description: 'Quiet Northwest Side neighborhood with single-family homes' },
  { id: 'norwood-park', name: 'Norwood Park', state: 'IL', type: 'neighborhood', region: 'north', coordinates: { lat: 41.9882, lng: -87.8025 }, zipCodes: ['60631'], nearbyAirports: { ORD: 6, MDW: 21 }, applicableServices: { airport: 18, corporate: 14, wedding: 15, partyBus: 14 }, description: 'Far Northwest Side neighborhood near O\'Hare with suburban feel' },
  { id: 'edison-park', name: 'Edison Park', state: 'IL', type: 'neighborhood', region: 'north', coordinates: { lat: 41.9923, lng: -87.8048 }, zipCodes: ['60631'], nearbyAirports: { ORD: 6, MDW: 22 }, applicableServices: { airport: 18, corporate: 14, wedding: 15, partyBus: 14 }, description: 'Far Northwest Side neighborhood closest to O\'Hare Airport' },
  { id: 'ohare', name: "O'Hare", state: 'IL', type: 'neighborhood', region: 'north', coordinates: { lat: 41.9742, lng: -87.9073 }, zipCodes: ['60666'], nearbyAirports: { ORD: 2, MDW: 24 }, applicableServices: { airport: 20, corporate: 16, wedding: 12, partyBus: 12 }, description: 'Airport district home to O\'Hare International Airport' },
  { id: 'irving-park', name: 'Irving Park', state: 'IL', type: 'neighborhood', region: 'north', coordinates: { lat: 41.9534, lng: -87.7373 }, zipCodes: ['60641'], nearbyAirports: { ORD: 12, MDW: 17 }, applicableServices: { airport: 17, corporate: 14, wedding: 15, partyBus: 15 }, description: 'Northwest Side neighborhood with diverse population and transit access' },
  { id: 'albany-park', name: 'Albany Park', state: 'IL', type: 'neighborhood', region: 'north', coordinates: { lat: 41.9689, lng: -87.7227 }, zipCodes: ['60625'], nearbyAirports: { ORD: 15, MDW: 19 }, applicableServices: { airport: 17, corporate: 14, wedding: 15, partyBus: 15 }, description: 'Diverse North Side neighborhood known as the "most diverse square mile"' },
  { id: 'north-park', name: 'North Park', state: 'IL', type: 'neighborhood', region: 'north', coordinates: { lat: 41.9867, lng: -87.7134 }, zipCodes: ['60625'], nearbyAirports: { ORD: 17, MDW: 21 }, applicableServices: { airport: 16, corporate: 14, wedding: 15, partyBus: 14 }, description: 'Quiet residential neighborhood on the North Side' },
  { id: 'dunning', name: 'Dunning', state: 'IL', type: 'neighborhood', region: 'north', coordinates: { lat: 41.9432, lng: -87.8190 }, zipCodes: ['60634'], nearbyAirports: { ORD: 7, MDW: 19 }, applicableServices: { airport: 17, corporate: 14, wedding: 14, partyBus: 14 }, description: 'Northwest Side neighborhood near O\'Hare with parks and schools' },
  { id: 'montclare', name: 'Montclare', state: 'IL', type: 'neighborhood', region: 'north', coordinates: { lat: 41.9207, lng: -87.7862 }, zipCodes: ['60634'], nearbyAirports: { ORD: 9, MDW: 17 }, applicableServices: { airport: 17, corporate: 13, wedding: 14, partyBus: 14 }, description: 'Small Northwest Side neighborhood with residential character' },
];

// Part 1 of location data - will continue in next part
export { CHICAGO_NEIGHBORHOODS, LocationData };
