import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { PrimaryButton, DangerButton } from "@/components/admin/buttons";
import { PlayCircle, FileText, Download, AlertCircle } from "lucide-react";
import { useAuth } from "@/contexts/AuthContext";

interface AuditResult {
  category: string;
  status: "pass" | "warning" | "fail";
  issues: string[];
  suggestions: string[];
}

export function FullAudit() {
  const { user } = useAuth();
  const [loading, setLoading] = useState(false);
  const [results, setResults] = useState<AuditResult[] | null>(null);
  const [reportPath, setReportPath] = useState<string>("");

  const runFullAudit = async () => {
    setLoading(true);

    // TODO: Implement actual audit checks
    // 1. Links check (broken internal links)
    // 2. SEO check (gate on all published)
    // 3. Images check (missing images)
    // 4. Sitemap check (valid XML)

    await new Promise((resolve) => setTimeout(resolve, 3000));

    const mockResults: AuditResult[] = [
      {
        category: "Internal Links",
        status: "warning",
        issues: ["3 broken internal links found", "1 redirect loop detected"],
        suggestions: [
          "Fix broken links in /services/corporate page",
          "Remove redirect loop in footer",
        ],
      },
      {
        category: "SEO Gates",
        status: "pass",
        issues: [],
        suggestions: ["All published pages pass quality gates"],
      },
      {
        category: "Images",
        status: "fail",
        issues: ["12 missing hero images", "5 vehicle pages with <8 images"],
        suggestions: [
          "Upload hero images for money pages",
          "Add vehicle interior shots",
        ],
      },
      {
        category: "Sitemap",
        status: "pass",
        issues: [],
        suggestions: ["All sitemaps valid XML", "847 URLs indexed"],
      },
      {
        category: "Performance",
        status: "warning",
        issues: ["2 pages with LCP >2.5s", "15 unoptimized images"],
        suggestions: ["Optimize images on /fleet page", "Enable lazy loading"],
      },
    ];

    setResults(mockResults);
    setReportPath(
      `/reports/full-audit-${new Date().toISOString().split("T")[0]}.md`,
    );
    setLoading(false);
  };

  const downloadReport = () => {
    // TODO: Generate and download markdown report
    const content = generateMarkdownReport(results || []);
    const blob = new Blob([content], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `audit-report-${new Date().toISOString().split("T")[0]}.md`;
    a.click();
  };

  const generateMarkdownReport = (results: AuditResult[]): string => {
    let report = `# Full Audit Report\n\n`;
    report += `**Generated:** ${new Date().toLocaleString()}\n`;
    report += `**Generated By:** ${user?.email}\n\n`;
    report += `---\n\n`;

    results.forEach((result) => {
      report += `## ${result.category}\n\n`;
      report += `**Status:** ${result.status.toUpperCase()}\n\n`;

      if (result.issues.length > 0) {
        report += `### Issues\n\n`;
        result.issues.forEach((issue) => {
          report += `- ${issue}\n`;
        });
        report += `\n`;
      }

      if (result.suggestions.length > 0) {
        report += `### Suggestions\n\n`;
        result.suggestions.forEach((suggestion) => {
          report += `- ${suggestion}\n`;
        });
        report += `\n`;
      }

      report += `---\n\n`;
    });

    return report;
  };

  const totalIssues =
    results?.reduce((sum, r) => sum + r.issues.length, 0) || 0;
  const failedCategories =
    results?.filter((r) => r.status === "fail").length || 0;

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">
            Full System Audit
          </h1>
          <p className="text-gray-600 mt-1">
            Comprehensive check of links, SEO, images, and sitemaps
          </p>
        </div>
        <PrimaryButton
          onClick={runFullAudit}
          loading={loading}
          disabled={loading}
        >
          <PlayCircle className="h-4 w-4" />
          Run Full Audit
        </PrimaryButton>
      </div>

      {/* Audit Checklist */}
      <Card>
        <CardHeader>
          <CardTitle>Audit Checks</CardTitle>
        </CardHeader>
        <CardContent>
          <ul className="space-y-2 text-sm">
            <li className="flex items-center gap-2">
              <span className="text-green-600">✓</span>
              <span>1. Links check (broken internal links)</span>
            </li>
            <li className="flex items-center gap-2">
              <span className="text-green-600">✓</span>
              <span>2. SEO check (gate on all published)</span>
            </li>
            <li className="flex items-center gap-2">
              <span className="text-green-600">✓</span>
              <span>3. Images check (missing images)</span>
            </li>
            <li className="flex items-center gap-2">
              <span className="text-green-600">✓</span>
              <span>4. Sitemap check (valid XML)</span>
            </li>
            <li className="flex items-center gap-2">
              <span className="text-green-600">✓</span>
              <span>5. Performance check (Core Web Vitals)</span>
            </li>
          </ul>
        </CardContent>
      </Card>

      {/* Results */}
      {results && (
        <>
          {/* Summary */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-sm font-medium">
                  Total Issues
                </CardTitle>
                <div className="text-3xl font-bold">{totalIssues}</div>
              </CardHeader>
            </Card>
            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-sm font-medium">
                  Failed Categories
                </CardTitle>
                <div className="text-3xl font-bold text-red-600">
                  {failedCategories}
                </div>
              </CardHeader>
            </Card>
            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-sm font-medium">Report</CardTitle>
                <div className="mt-2">
                  <PrimaryButton size="sm" onClick={downloadReport}>
                    <Download className="h-3 w-3" />
                    Download
                  </PrimaryButton>
                </div>
              </CardHeader>
            </Card>
          </div>

          {/* Detailed Results */}
          <div className="space-y-4">
            {results.map((result, index) => (
              <Card key={index}>
                <CardHeader>
                  <div className="flex items-center justify-between">
                    <CardTitle className="flex items-center gap-2">
                      {result.status === "fail" && (
                        <AlertCircle className="h-5 w-5 text-red-600" />
                      )}
                      {result.category}
                    </CardTitle>
                    <span
                      className={`px-3 py-1 rounded-full text-sm font-medium ${
                        result.status === "pass"
                          ? "bg-green-100 text-green-800"
                          : result.status === "warning"
                            ? "bg-yellow-100 text-yellow-800"
                            : "bg-red-100 text-red-800"
                      }`}
                    >
                      {result.status.toUpperCase()}
                    </span>
                  </div>
                </CardHeader>
                <CardContent>
                  {result.issues.length > 0 && (
                    <div className="mb-4">
                      <h4 className="font-semibold text-sm mb-2 text-red-600">
                        Issues:
                      </h4>
                      <ul className="space-y-1 text-sm">
                        {result.issues.map((issue, i) => (
                          <li key={i} className="flex items-start gap-2">
                            <span className="text-red-600">✗</span>
                            <span>{issue}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                  {result.suggestions.length > 0 && (
                    <div>
                      <h4 className="font-semibold text-sm mb-2 text-blue-600">
                        Suggestions:
                      </h4>
                      <ul className="space-y-1 text-sm">
                        {result.suggestions.map((suggestion, i) => (
                          <li key={i} className="flex items-start gap-2">
                            <span className="text-blue-600">→</span>
                            <span>{suggestion}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                </CardContent>
              </Card>
            ))}
          </div>

          {reportPath && (
            <Card>
              <CardContent className="pt-6">
                <div className="flex items-center gap-4">
                  <FileText className="h-8 w-8 text-gray-400" />
                  <div className="flex-1">
                    <p className="text-sm font-medium">Report Generated</p>
                    <p className="text-xs text-gray-500">{reportPath}</p>
                  </div>
                  <PrimaryButton onClick={downloadReport}>
                    <Download className="h-4 w-4" />
                    Download Report
                  </PrimaryButton>
                </div>
              </CardContent>
            </Card>
          )}
        </>
      )}
    </div>
  );
}
